"""Base reward interface for extensible reward design.

Aligned with the Self-Evolving ICL framework (asymmetric adversarial play):
  - Challenger generates (Q, E, R) from context C
  - Solver generates answer A from (C, Q)
  - Judge scores A against R and verifies (Q, R) validity
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class SolverRewardResult:
    """Structured result for solver reward computation.

    The Solver objective maximizes J_score(A, R) — the Judge's evaluation
    of Answer A against the Challenger's Rubric R.
    """

    total: float = 0.0
    correctness: float = 0.0
    context_grounding: float = 0.0
    tool_usage: float = 0.0
    details: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ChallengeRewardResult:
    """Structured result for challenge reward computation.

    Five components from the self-evolving framework:
      1. R_adv   = 1 - J_score(A, R)            adversarial reward
      2. R_rep   = cluster penalty               repetition penalty
      3. R_fmt   = binary format check            format penalty
      4. R_rel   = BLEU(Q,C) · I[J_ans(Q,C)]    context relevance
      5. R_rubric= Sim(R,E) · J_align(R,E,C)    rubric quality
    """

    total: float = 0.0
    adversarial: float = 0.0
    repetition_penalty: float = 0.0
    format_penalty: float = 0.0
    relevance: float = 0.0
    rubric_quality: float = 0.0
    details: Dict[str, Any] = field(default_factory=dict)

    @property
    def correctness(self) -> float:
        """Backward-compatible alias for adversarial reward."""
        return self.adversarial

    @correctness.setter
    def correctness(self, value: float) -> None:
        self.adversarial = value


class BaseReward(ABC):
    """Abstract base class for dual rewards (Solver + Challenge)."""

    @abstractmethod
    def compute_solver_reward(
        self,
        answer: str,
        rubrics: List[str],
        context: str,
        metadata: Dict[str, Any],
        **kwargs,
    ) -> SolverRewardResult:
        """
        Compute reward for the Solver model based on its answer.

        Args:
            answer: Solver's generated answer.
            rubrics: List of evaluation criteria.
            context: The full context provided to the solver.
            metadata: Task metadata (task_id, context_id, context_category, sub_category).
            **kwargs: Additional context (e.g., challenge_output, messages).

        Returns:
            SolverRewardResult with breakdown of reward components.
        """
        pass

    @abstractmethod
    def compute_challenge_reward(
        self,
        solver_correctness: float,
        challenge_output: str,
        context: str,
        question: str,
        rubrics: List[str],
        metadata: Dict[str, Any],
        evidence_span: str = "",
        **kwargs,
    ) -> ChallengeRewardResult:
        """
        Compute reward for the Challenge model.

        Args:
            solver_correctness: J_score(A, R) from solver evaluation (0.0-1.0).
            challenge_output: Raw text generated by the challenge model.
            context: Original context C provided to challenge model.
            question: Question Q generated by challenge model.
            rubrics: Rubrics R generated by challenge model.
            metadata: Task metadata.
            evidence_span: Evidence span E extracted from context by the challenger.
            **kwargs: Additional context (e.g., batch_repetition_penalty).

        Returns:
            ChallengeRewardResult with breakdown of reward components.
        """
        pass
